name: Build Aseprite EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      uses: aseprite/get-ninja@main

    - name: Download Skia
      shell: bash
      run: |
        skia_url=$(source laf/misc/skia-url.sh | xargs)
        skia_file=$(basename $skia_url)
        curl -L -o "$skia_file" "$skia_url"
        unzip "$skia_file" -d skia

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DLAF_BACKEND=skia \
          -DENABLE_SCRIPTING=ON \
          -DSKIA_DIR=$(realpath skia) \
          -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-x64)

    - name: Build
      shell: bash
      run: |
        cd build
        ninja

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-exe
        path: build/bin/aseprite.exe
